### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by drinksi** [syampillai/SOSample#5]
The demo for SoComponents is not working.  It returns a blank page.

**Comment by ClancyDamon** [comment]
Seconding this.

When I try and run the application exactly as is using both Corretto 21 and Corretto 17, I consistently get the following when accessing localhost:8080:

`
Caused by: java.lang.IllegalStateException: Webpack exited prematurely
	at com.vaadin.base.devserver.AbstractDevServerRunner.doStartDevModeServer(AbstractDevServerRunner.java:220)
	at com.vaadin.base.devserver.AbstractDevServerRunner.runOnFutureComplete(AbstractDevServerRunner.java:172)
	at com.vaadin.base.devserver.AbstractDevServerRunner.lambda$new$0(AbstractDevServerRunner.java:163)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
`

I did try and upgrade things. I updated vaadin.version to 24.5.3, the jetty.version to 11.0.24, and the so-components to 11.1.21. This, however, results in errors that are apparently in the so-components code itself:

`
Caused by: java.lang.NoSuchMethodError: 'void com.storedobject.vaadin.Alert.addThemeVariants(com.vaadin.flow.component.notification.NotificationVariant[])'
	at com.storedobject.vaadin.Alert.<init>(Alert.java:137)
	at com.storedobject.vaadin.Alert.<init>(Alert.java:109)
	at com.storedobject.vaadin.Alert.<init>(Alert.java:75)
	at com.storedobject.sample.App$AppView.createApplication(App.java:37)
	at com.storedobject.vaadin.ApplicationView.<init>(ApplicationView.java:52)
	at com.storedobject.sample.App$AppView.<init>(App.java:33)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 74 more
`

I modified the App.java as a test, and found that the main problem is trying to provide a NotificationVariant to the constructor:

```
    @Route("")
    public static class AppView extends ApplicationView {

        @Override
        protected Application createApplication() {
            /**
             * This works with no issue
             */
            Alert test2 = new Alert("Hello");
            test2.addThemeVariants(NotificationVariant.LUMO_PRIMARY);

            /**
             * This fails everytime
             */
            Alert test = new Alert("Hello", NotificationVariant.LUMO_PRIMARY);

            return new App();
        }
    }
```

So, it seems to be that the following field in the Application.java class doesn't work:
```
private final Alert errorText = new Alert(null, NotificationVariant.LUMO_PRIMARY);
```

Because that eventually hits the protected constructor for alert, and the 'addThemeVariant' fails everytime I try to provide a 'style' constructor param:

```
    protected Alert(StyledText htmlContent, Consumer<Alert> clickAction, NotificationVariant style) {
        this.clickAction = clickAction;
        content = htmlContent;
        content.getElement().getStyle().set("cursor", "pointer");
        add(content);
        click = new ElementClick(content);
        addClickListener(e -> clicked());
        if(style != null) {
            addThemeVariants(style); //This line causes a complete failure of the application.
        }
        setPosition(DEFAULT_POSITION);
    }
```

This baffles me because the 'addThemeVariants' method very clearly DOES exist, but seems to only exist post-constructor?
